### ISSUE TITLE
Error use images in items

### ISSUE THREAD

**Issue by volkdown** [michael-rapp/AndroidBottomSheet#9]
Hello! I get next error? when use add items with icons

```
BottomSheet.Builder builder = new BottomSheet.Builder(this);
        builder.addItem(0, R.string.facebook_app_id, R.drawable.user_logo);
        builder.addItem(1, R.string.facebook_app_id, R.drawable.user_logo);
        builder.addDivider();
        mBottomSheet = builder.create();
        mBottomSheet.show();
```

```
12-25 20:40:34.087 31758-31758/com.softinlife.inventapp E/AndroidRuntime: FATAL EXCEPTION: main
                                                                          Process: com.softinlife.inventapp, PID: 31758
                                                                          java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.ImageView.setVisibility(int)' on a null object reference
                                                                              at de.mrapp.android.bottomsheet.adapter.DividableGridAdapter.visualizeItem(DividableGridAdapter.java:251)
                                                                              at de.mrapp.android.bottomsheet.adapter.DividableGridAdapter.getView(DividableGridAdapter.java:658)
                                                                              at android.widget.AbsListView.obtainView(AbsListView.java:2347)
                                                                              at android.widget.GridView.onMeasure(GridView.java:1060)
                                                                              at android.view.View.measure(View.java:17585)
                                                                              at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:728)
                                                                              at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:464)
                                                                              at android.view.View.measure(View.java:17585)
                                                                              at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5536)
                                                                              at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1436)
                                                                              at android.widget.LinearLayout.measureVertical(LinearLayout.java:722)
                                                                              at android.widget.LinearLayout.onMeasure(LinearLayout.java:613)
                                                                              at de.mrapp.android.bottomsheet.view.DraggableView.onMeasure(DraggableView.java:636)
                                                                              at android.view.View.measure(View.java:17585)
                                                                              at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5536)
                                                                              at android.widget.FrameLayout.onMeasure(FrameLayout.java:436)
                                                                              at android.view.View.measure(View.java:17585)
                                                                              at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5536)
                                                                              at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1436)
                                                                              at android.widget.LinearLayout.measureVertical(LinearLayout.java:722)
                                                                              at android.widget.LinearLayout.onMeasure(LinearLayout.java:613)
                                                                              at android.view.View.measure(View.java:17585)
                                                                              at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5536)
                                                                              at android.widget.FrameLayout.onMeasure(FrameLayout.java:436)
                                                                              at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2618)
                                                                              at android.view.View.measure(View.java:17585)
                                                                              at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2033)
                                                                              at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1191)
                                                                              at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1397)
                                                                              at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1079)
                                                                              at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5914)
                                                                              at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
                                                                              at android.view.Choreographer.doCallbacks(Choreographer.java:580)
                                                                              at android.view.Choreographer.doFrame(Choreographer.java:550)
                                                                              at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
                                                                              at android.os.Handler.handleCallback(Handler.java:739)
                                                                              at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                              at android.os.Looper.loop(Looper.java:135)
                                                                              at android.app.ActivityThread.main(ActivityThread.java:5275)
                                                                              at java.lang.reflect.Method.invoke(Native Method)
                                                                              at java.lang.reflect.Method.invoke(Method.java:372)
                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:910)
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:705)
```
Thanks in advance for your reply!)

**Comment by michael-rapp** [comment]
Hello,

sorry for the late reply. I tried to reproduce your problem, but I 
wasn't able to do so. The sample you've sent to me, works fine for me. 
I also took a look at the library's code, but I couldn't find an 
obvious bug, which may cause the NullPointerException.

Without more information, it is really hard for me to figure out this 
issue. What kind of icons do you use? Are these image resources or XML 
drawables? Does it work without icons? What style does your bottom 
sheet have? List, columns or grid? Does the error occur every time you 
want to show the bottom sheet? If so, maybe you can send me a working 
code example. Alternatively, you could debug the getView-method in the 
class DividableGridAdapter. This is the place, where something must go 
wrong.

Regards,
Michael

**Comment by michael-rapp** [comment]
Issue will be re-opened, once more information is available.
